class HostInfoBeanClass:
    def __init__(self):
        self.ip = ''
        self.port = ''
        self.msg = ''
        self.hostname = ''
        self.in_ip = ''
        self.os_type = ''
        self.os_version = ''
        self.mem_total = ''
        self.mem_swap = ''
        self.cpu_type = ''
        self.cpu_num = ''
        self.disk_info = ''
        self.kernel = ''
        self.status = ''