# Generated by Django 2.1.4 on 2019-02-03 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cproom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, null=True)),
                ('describe', models.CharField(max_length=256, null=True)),
                ('address', models.CharField(max_length=128, null=True)),
                ('contacts', models.CharField(max_length=24, null=True)),
                ('telephone', models.CharField(max_length=11, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HostGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, null=True)),
                ('describe', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HostGroupRel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='HostInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=64, unique=True)),
                ('port', models.CharField(default='5100', max_length=8)),
                ('msg', models.CharField(max_length=64, null=True)),
                ('hostname', models.CharField(max_length=64, null=True)),
                ('in_ip', models.CharField(max_length=64, null=True)),
                ('os_type', models.CharField(max_length=64, null=True)),
                ('os_version', models.CharField(max_length=64, null=True)),
                ('mem_total', models.CharField(max_length=64, null=True)),
                ('mem_swap', models.CharField(default='0', max_length=32)),
                ('cpu_type', models.CharField(max_length=64, null=True)),
                ('cpu_num', models.CharField(max_length=16, null=True)),
                ('disk_info', models.CharField(max_length=512, null=True)),
                ('kernel', models.CharField(max_length=64, null=True)),
                ('status', models.CharField(max_length=16, null=True)),
                ('addTime', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assetManagement.Cproom')),
            ],
        ),
        migrations.AddField(
            model_name='hostgrouprel',
            name='host1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host', to='assetManagement.HostInfo'),
        ),
        migrations.AddField(
            model_name='hostgrouprel',
            name='hostgroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostgroup', to='assetManagement.HostGroup'),
        ),
    ]
