# Generated by Django 2.1.4 on 2019-02-03 01:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assetManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(max_length=256)),
                ('server_version', models.CharField(max_length=512, null=True)),
                ('server_port', models.CharField(max_length=1026, null=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assetManagement.HostInfo')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=128, null=True)),
                ('Photo', models.CharField(max_length=256, null=True)),
                ('status', models.CharField(default='离线', max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
